//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HW.MobileApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnglishResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnglishResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HW.MobileApp.Properties.EnglishResources", typeof(EnglishResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © HealthWatch 2014&lt;br /&gt;All Rights Reserved.
        /// </summary>
        internal static string about_copyright {
            get {
                return ResourceManager.GetString("about.copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HealthWatch provides tools for individuals and organisations to preserve and increase health and quality of life, as well as reduce stress-related problems..
        /// </summary>
        internal static string about_text {
            get {
                return ResourceManager.GetString("about.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string about_title {
            get {
                return ResourceManager.GetString("about.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string button_back {
            get {
                return ResourceManager.GetString("button.back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Login Page.
        /// </summary>
        internal static string button_backToLogin {
            get {
                return ResourceManager.GetString("button.backToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string button_cancel {
            get {
                return ResourceManager.GetString("button.cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string button_contactUs {
            get {
                return ResourceManager.GetString("button.contactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string button_done {
            get {
                return ResourceManager.GetString("button.done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Us.
        /// </summary>
        internal static string button_emailUs {
            get {
                return ResourceManager.GetString("button.emailUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started!.
        /// </summary>
        internal static string button_getStarted {
            get {
                return ResourceManager.GetString("button.getStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string button_save {
            get {
                return ResourceManager.GetString("button.save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        internal static string calendar_title {
            get {
                return ResourceManager.GetString("calendar.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        internal static string contact_publisher {
            get {
                return ResourceManager.GetString("contact.publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string contact_title {
            get {
                return ResourceManager.GetString("contact.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diary.
        /// </summary>
        internal static string dashboard_diary {
            get {
                return ResourceManager.GetString("dashboard.diary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercises.
        /// </summary>
        internal static string dashboard_exercises {
            get {
                return ResourceManager.GetString("dashboard.exercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form.
        /// </summary>
        internal static string dashboard_form {
            get {
                return ResourceManager.GetString("dashboard.form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report an Issue.
        /// </summary>
        internal static string dashboard_reportIssue {
            get {
                return ResourceManager.GetString("dashboard.reportIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always show on start.
        /// </summary>
        internal static string default_start {
            get {
                return ResourceManager.GetString("default.start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string diary_date {
            get {
                return ResourceManager.GetString("diary.date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mood.
        /// </summary>
        internal static string diary_mood {
            get {
                return ResourceManager.GetString("diary.mood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t Know&lt;div&gt;&lt;img class=&apos;image&apos; src=&apos;http://clients.easyapp.se/healthwatch/images/dontKnow@2x.png&apos;&gt;&lt;/div&gt;.
        /// </summary>
        internal static string diary_mood_dontknow {
            get {
                return ResourceManager.GetString("diary.mood.dontknow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Happy&lt;div&gt;&lt;img class=&apos;image&apos; src=&apos;http://clients.easyapp.se/healthwatch/images/happy@2x.png&apos;&gt;&lt;/div&gt;.
        /// </summary>
        internal static string diary_mood_happy {
            get {
                return ResourceManager.GetString("diary.mood.happy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral&lt;div&gt;&lt;img class=&apos;image&apos; src=&apos;http://clients.easyapp.se/healthwatch/images/neutral@2x.png&apos;&gt;&lt;/div&gt;.
        /// </summary>
        internal static string diary_mood_neutral {
            get {
                return ResourceManager.GetString("diary.mood.neutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhappy&lt;div&gt;&lt;img class=&apos;image&apos; src=&apos;http://clients.easyapp.se/healthwatch/images/unhappy@2x.png&apos;&gt;&lt;/div&gt;.
        /// </summary>
        internal static string diary_mood_unhappy {
            get {
                return ResourceManager.GetString("diary.mood.unhappy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string diary_notes {
            get {
                return ResourceManager.GetString("diary.notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphabetical.
        /// </summary>
        internal static string exercise_alphabetical {
            get {
                return ResourceManager.GetString("exercise.alphabetical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular.
        /// </summary>
        internal static string exercise_popular {
            get {
                return ResourceManager.GetString("exercise.popular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        internal static string exercise_random {
            get {
                return ResourceManager.GetString("exercise.random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all exercises.
        /// </summary>
        internal static string exercise_viewAll {
            get {
                return ResourceManager.GetString("exercise.viewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        internal static string faq_title {
            get {
                return ResourceManager.GetString("faq.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string home_logout {
            get {
                return ResourceManager.GetString("home.logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string home_more {
            get {
                return ResourceManager.GetString("home.more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Health.
        /// </summary>
        internal static string home_myHealth {
            get {
                return ResourceManager.GetString("home.myHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        internal static string home_news {
            get {
                return ResourceManager.GetString("home.news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to Start.
        /// </summary>
        internal static string home_tap {
            get {
                return ResourceManager.GetString("home.tap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string issue_description {
            get {
                return ResourceManager.GetString("issue.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string issue_title {
            get {
                return ResourceManager.GetString("issue.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields with &lt;span style=&quot;color:Red;&quot;&gt;*&lt;/span&gt; are required.
        /// </summary>
        internal static string label_required {
            get {
                return ResourceManager.GetString("label.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you! The link to create a new password has been sent. Kindly check your email..
        /// </summary>
        internal static string link_message {
            get {
                return ResourceManager.GetString("link.message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link sent.
        /// </summary>
        internal static string link_sent {
            get {
                return ResourceManager.GetString("link.sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to a better life..
        /// </summary>
        internal static string login_message {
            get {
                return ResourceManager.GetString("login.message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No activities and measurements.
        /// </summary>
        internal static string measurement_none {
            get {
                return ResourceManager.GetString("measurement.none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities &amp; Measurements.
        /// </summary>
        internal static string measurement_text {
            get {
                return ResourceManager.GetString("measurement.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View/Add Activities and Measurements.
        /// </summary>
        internal static string measurement_viewAdd {
            get {
                return ResourceManager.GetString("measurement.viewAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About HealthWatch.
        /// </summary>
        internal static string more_about {
            get {
                return ResourceManager.GetString("more.about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like us on Facebook.
        /// </summary>
        internal static string more_like {
            get {
                return ResourceManager.GetString("more.like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell a Friend.
        /// </summary>
        internal static string more_tell {
            get {
                return ResourceManager.GetString("more.tell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all news.
        /// </summary>
        internal static string news_all {
            get {
                return ResourceManager.GetString("news.all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string news_categories {
            get {
                return ResourceManager.GetString("news.categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International.
        /// </summary>
        internal static string news_categories_international {
            get {
                return ResourceManager.GetString("news.categories.international", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a category to view.
        /// </summary>
        internal static string news_categories_select {
            get {
                return ResourceManager.GetString("news.categories.select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swedish.
        /// </summary>
        internal static string news_categories_swedish {
            get {
                return ResourceManager.GetString("news.categories.swedish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string news_summary {
            get {
                return ResourceManager.GetString("news.summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All News.
        /// </summary>
        internal static string news_text {
            get {
                return ResourceManager.GetString("news.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose one....
        /// </summary>
        internal static string options_choose {
            get {
                return ResourceManager.GetString("options.choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string options_compare_database {
            get {
                return ResourceManager.GetString("options.compare.database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string options_compare_none {
            get {
                return ResourceManager.GetString("options.compare.none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest.
        /// </summary>
        internal static string options_timeframe_latest {
            get {
                return ResourceManager.GetString("options.timeframe.latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past month.
        /// </summary>
        internal static string options_timeframe_pastMonth {
            get {
                return ResourceManager.GetString("options.timeframe.pastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past week.
        /// </summary>
        internal static string options_timeframe_pastWeek {
            get {
                return ResourceManager.GetString("options.timeframe.pastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past year.
        /// </summary>
        internal static string options_timeframe_pastYear {
            get {
                return ResourceManager.GetString("options.timeframe.pastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since first measure.
        /// </summary>
        internal static string options_timeframe_sinceFirstMeasure {
            get {
                return ResourceManager.GetString("options.timeframe.sinceFirstMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Profile.
        /// </summary>
        internal static string profile_title {
            get {
                return ResourceManager.GetString("profile.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I accept.
        /// </summary>
        internal static string register_accept {
            get {
                return ResourceManager.GetString("register.accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string register_create {
            get {
                return ResourceManager.GetString("register.create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp; Conditions of the Service.
        /// </summary>
        internal static string register_terms {
            get {
                return ResourceManager.GetString("register.terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string register_title {
            get {
                return ResourceManager.GetString("register.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminders.
        /// </summary>
        internal static string reminder_title {
            get {
                return ResourceManager.GetString("reminder.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Profile.
        /// </summary>
        internal static string settings_changeProfile {
            get {
                return ResourceManager.GetString("settings.changeProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language, email address and personal information.
        /// </summary>
        internal static string settings_changeProfile_description {
            get {
                return ResourceManager.GetString("settings.changeProfile.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminders.
        /// </summary>
        internal static string settings_reminders {
            get {
                return ResourceManager.GetString("settings.reminders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        internal static string settings_reminders_description {
            get {
                return ResourceManager.GetString("settings.reminders.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options for automatic login.
        /// </summary>
        internal static string settings_security_description {
            get {
                return ResourceManager.GetString("settings.security.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay logged in.
        /// </summary>
        internal static string settings_security_login {
            get {
                return ResourceManager.GetString("settings.security.login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Settings.
        /// </summary>
        internal static string settings_security_title {
            get {
                return ResourceManager.GetString("settings.security.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show welcome page.
        /// </summary>
        internal static string settings_security_welcome {
            get {
                return ResourceManager.GetString("settings.security.welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settings_title {
            get {
                return ResourceManager.GetString("settings.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Plan.
        /// </summary>
        internal static string statistics_action {
            get {
                return ResourceManager.GetString("statistics.action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare with.
        /// </summary>
        internal static string statistics_compare {
            get {
                return ResourceManager.GetString("statistics.compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healthy level.
        /// </summary>
        internal static string statistics_healthy {
            get {
                return ResourceManager.GetString("statistics.healthy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improvement needed.
        /// </summary>
        internal static string statistics_improvement {
            get {
                return ResourceManager.GetString("statistics.improvement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpretation.
        /// </summary>
        internal static string statistics_interpretation {
            get {
                return ResourceManager.GetString("statistics.interpretation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string statistics_result {
            get {
                return ResourceManager.GetString("statistics.result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string statistics_title {
            get {
                return ResourceManager.GetString("statistics.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhealthy level.
        /// </summary>
        internal static string statistics_unhealthy {
            get {
                return ResourceManager.GetString("statistics.unhealthy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What can the diary be used for?.
        /// </summary>
        internal static string support_calendar {
            get {
                return ResourceManager.GetString("support.calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The diary can be used to write down your thoughts and feelings,which has been shown to efficently reduce anxiety and stress. There is both a typing mode and a read mode in the diary and you can also add other activities and measurements, such as physical activity, blood pressure and BMI for example. You can also see which exercises you have done and how you have responded to your forms at certain days..
        /// </summary>
        internal static string support_calendar_description {
            get {
                return ResourceManager.GetString("support.calendar.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do I change my Email Address?.
        /// </summary>
        internal static string support_changeEmail {
            get {
                return ResourceManager.GetString("support.changeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can change your email address by tapping the icon for ‘Settings’ which is placed on the top corner of ‘My Health’. Tap ‘Change Profile’ and fill in your new email address. Thereafter tap ‘Save’..
        /// </summary>
        internal static string support_changeEmail_description {
            get {
                return ResourceManager.GetString("support.changeEmail.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More FAQs.
        /// </summary>
        internal static string support_faq {
            get {
                return ResourceManager.GetString("support.faq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More frequently asked questions will be displayed here shortly. Thank you for your patience..
        /// </summary>
        internal static string support_faq_descriptioin {
            get {
                return ResourceManager.GetString("support.faq.descriptioin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do I track my health?.
        /// </summary>
        internal static string support_healthTrack {
            get {
                return ResourceManager.GetString("support.healthTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track your health development over time by responding to the 11 questions in the Form. Once you save, you get immediate individual feedback and an action plan. When clicking the exercises in the action plan you will be directed to Exercises. You may also view your development over time by clicking ‘View’. You can choose to view one question at a time or several in the same graph..
        /// </summary>
        internal static string support_healthTrack_description {
            get {
                return ResourceManager.GetString("support.healthTrack.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        internal static string support_title {
            get {
                return ResourceManager.GetString("support.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Details.
        /// </summary>
        internal static string user_account {
            get {
                return ResourceManager.GetString("user.account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate Email.
        /// </summary>
        internal static string user_alternateEmail {
            get {
                return ResourceManager.GetString("user.alternateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        internal static string user_confirmPassword {
            get {
                return ResourceManager.GetString("user.confirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create account.
        /// </summary>
        internal static string user_createAccount {
            get {
                return ResourceManager.GetString("user.createAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string user_email {
            get {
                return ResourceManager.GetString("user.email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email address below, and we will send you a link that can be used to create a new password..
        /// </summary>
        internal static string user_forgot_message {
            get {
                return ResourceManager.GetString("user.forgot.message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        internal static string user_forgot_password {
            get {
                return ResourceManager.GetString("user.forgot.password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something is wrong.
        /// </summary>
        internal static string user_forgot_wrong {
            get {
                return ResourceManager.GetString("user.forgot.wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no such user with that email address. Please enter the email address that is connected to your account.
        /// </summary>
        internal static string user_forgot_wrongMessage {
            get {
                return ResourceManager.GetString("user.forgot.wrongMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        internal static string user_forgotPassword {
            get {
                return ResourceManager.GetString("user.forgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, incorrect login details..
        /// </summary>
        internal static string user_incorrectLogin {
            get {
                return ResourceManager.GetString("user.incorrectLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        internal static string user_info {
            get {
                return ResourceManager.GetString("user.info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string user_language {
            get {
                return ResourceManager.GetString("user.language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string user_login {
            get {
                return ResourceManager.GetString("user.login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or Email.
        /// </summary>
        internal static string user_name {
            get {
                return ResourceManager.GetString("user.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string user_password {
            get {
                return ResourceManager.GetString("user.password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp; Conditions of the Service.
        /// </summary>
        internal static string user_terms {
            get {
                return ResourceManager.GetString("user.terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string user_username {
            get {
                return ResourceManager.GetString("user.username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare with.
        /// </summary>
        internal static string view_compare {
            get {
                return ResourceManager.GetString("view.compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select results to view &amp; compare.
        /// </summary>
        internal static string view_select {
            get {
                return ResourceManager.GetString("view.select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeframe.
        /// </summary>
        internal static string view_timeframe {
            get {
                return ResourceManager.GetString("view.timeframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View....
        /// </summary>
        internal static string view_title {
            get {
                return ResourceManager.GetString("view.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diary.
        /// </summary>
        internal static string welcome_diary {
            get {
                return ResourceManager.GetString("welcome.diary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View daily activities and log your thoughts and feelings..
        /// </summary>
        internal static string welcome_diary_description {
            get {
                return ResourceManager.GetString("welcome.diary.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercises.
        /// </summary>
        internal static string welcome_exercise {
            get {
                return ResourceManager.GetString("welcome.exercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn exercises that help improve your overall health..
        /// </summary>
        internal static string welcome_exercise_description {
            get {
                return ResourceManager.GetString("welcome.exercise.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form.
        /// </summary>
        internal static string welcome_form {
            get {
                return ResourceManager.GetString("welcome.form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor your health and stress levels by filling out the form on a regular basis..
        /// </summary>
        internal static string welcome_form_description {
            get {
                return ResourceManager.GetString("welcome.form.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for creating an account with us! Here are a few things that you need to know in order to get started on or continue with a healthier and happier life:.
        /// </summary>
        internal static string welcome_message {
            get {
                return ResourceManager.GetString("welcome.message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor your progress over time and do the recommended exercises..
        /// </summary>
        internal static string welcome_statistics_description {
            get {
                return ResourceManager.GetString("welcome.statistics.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to HealthWatch!.
        /// </summary>
        internal static string welcome_title {
            get {
                return ResourceManager.GetString("welcome.title", resourceCulture);
            }
        }
    }
}
