//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HW.Invoicing.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class sv_SE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal sv_SE() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HW.Invoicing.Core.Properties.sv-SE", typeof(sv_SE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postadress.
        /// </summary>
        internal static string company_address_postal {
            get {
                return ResourceManager.GetString("company.address.postal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bankgiro.
        /// </summary>
        internal static string company_bank {
            get {
                return ResourceManager.GetString("company.bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Org nr.
        /// </summary>
        internal static string company_org {
            get {
                return ResourceManager.GetString("company.org", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        internal static string company_phone {
            get {
                return ResourceManager.GetString("company.phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F-skattebevis.
        /// </summary>
        internal static string company_tax {
            get {
                return ResourceManager.GetString("company.tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT/Momsreg.nr.
        /// </summary>
        internal static string company_vat {
            get {
                return ResourceManager.GetString("company.vat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        internal static string company_web {
            get {
                return ResourceManager.GetString("company.web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beställare/Leveransadress/Faktureringsadress.
        /// </summary>
        internal static string customer {
            get {
                return ResourceManager.GetString("customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KUNDNUMMER.
        /// </summary>
        internal static string customer_number {
            get {
                return ResourceManager.GetString("customer.number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAKTURADATUM.
        /// </summary>
        internal static string invoice_date {
            get {
                return ResourceManager.GetString("invoice.date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FÖRFALLODAG.
        /// </summary>
        internal static string invoice_date_maturity {
            get {
                return ResourceManager.GetString("invoice.date.maturity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAKTURA.
        /// </summary>
        internal static string invoice_label {
            get {
                return ResourceManager.GetString("invoice.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAKTURANUMMER.
        /// </summary>
        internal static string invoice_number {
            get {
                return ResourceManager.GetString("invoice.number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vår referens:.
        /// </summary>
        internal static string invoice_reference_our {
            get {
                return ResourceManager.GetString("invoice.reference.our", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er referens:.
        /// </summary>
        internal static string invoice_reference_your {
            get {
                return ResourceManager.GetString("invoice.reference.your", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUBTOTAL.
        /// </summary>
        internal static string invoice_subtotal_ {
            get {
                return ResourceManager.GetString("invoice.subtotal\"", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betalningsvillkor: 30 dagar netto. Vid likvid efter förfallodagen debiteras ränta med 2% per månad..
        /// </summary>
        internal static string invoice_terms {
            get {
                return ResourceManager.GetString("invoice.terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUMMA ATT BETALA.
        /// </summary>
        internal static string invoice_total {
            get {
                return ResourceManager.GetString("invoice.total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOMS %.
        /// </summary>
        internal static string invoice_vat {
            get {
                return ResourceManager.GetString("invoice.vat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOMS.
        /// </summary>
        internal static string invoice_vat_amount {
            get {
                return ResourceManager.GetString("invoice.vat.amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPECIFIKATION.
        /// </summary>
        internal static string item {
            get {
                return ResourceManager.GetString("item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BELOPP.
        /// </summary>
        internal static string item_amount {
            get {
                return ResourceManager.GetString("item.amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRIS.
        /// </summary>
        internal static string item_price {
            get {
                return ResourceManager.GetString("item.price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRIS PER ENHET.
        /// </summary>
        internal static string item_price_unit {
            get {
                return ResourceManager.GetString("item.price.unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANTAL.
        /// </summary>
        internal static string item_quantity {
            get {
                return ResourceManager.GetString("item.quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENHET.
        /// </summary>
        internal static string item_unit {
            get {
                return ResourceManager.GetString("item.unit", resourceCulture);
            }
        }
    }
}
