//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace HW.Grp.WebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SoapSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseModel))]
    public partial class Soap : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ManagerLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback SuperAdminTokenOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDepartmentTreeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUsersInDepartmentOperationCompleted;
        
        private System.Threading.SendOrPostCallback ManagerLogOutOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Soap() {
            this.Url = global::HW.Grp.Properties.Settings.Default.HW_Grp_WebService_Soap;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ManagerLoginCompletedEventHandler ManagerLoginCompleted;
        
        /// <remarks/>
        public event SuperAdminTokenCompletedEventHandler SuperAdminTokenCompleted;
        
        /// <remarks/>
        public event GetDepartmentTreeCompletedEventHandler GetDepartmentTreeCompleted;
        
        /// <remarks/>
        public event GetUsersInDepartmentCompletedEventHandler GetUsersInDepartmentCompleted;
        
        /// <remarks/>
        public event ManagerLogOutCompletedEventHandler ManagerLogOutCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ManagerLogin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SponsorAdministrator ManagerLogin(string username, string password, int expirationMinutes) {
            object[] results = this.Invoke("ManagerLogin", new object[] {
                        username,
                        password,
                        expirationMinutes});
            return ((SponsorAdministrator)(results[0]));
        }
        
        /// <remarks/>
        public void ManagerLoginAsync(string username, string password, int expirationMinutes) {
            this.ManagerLoginAsync(username, password, expirationMinutes, null);
        }
        
        /// <remarks/>
        public void ManagerLoginAsync(string username, string password, int expirationMinutes, object userState) {
            if ((this.ManagerLoginOperationCompleted == null)) {
                this.ManagerLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnManagerLoginOperationCompleted);
            }
            this.InvokeAsync("ManagerLogin", new object[] {
                        username,
                        password,
                        expirationMinutes}, this.ManagerLoginOperationCompleted, userState);
        }
        
        private void OnManagerLoginOperationCompleted(object arg) {
            if ((this.ManagerLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ManagerLoginCompleted(this, new ManagerLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SuperAdminToken", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SponsorAdministrator SuperAdminToken(string token, int sponsorID, int expirationMinutes) {
            object[] results = this.Invoke("SuperAdminToken", new object[] {
                        token,
                        sponsorID,
                        expirationMinutes});
            return ((SponsorAdministrator)(results[0]));
        }
        
        /// <remarks/>
        public void SuperAdminTokenAsync(string token, int sponsorID, int expirationMinutes) {
            this.SuperAdminTokenAsync(token, sponsorID, expirationMinutes, null);
        }
        
        /// <remarks/>
        public void SuperAdminTokenAsync(string token, int sponsorID, int expirationMinutes, object userState) {
            if ((this.SuperAdminTokenOperationCompleted == null)) {
                this.SuperAdminTokenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSuperAdminTokenOperationCompleted);
            }
            this.InvokeAsync("SuperAdminToken", new object[] {
                        token,
                        sponsorID,
                        expirationMinutes}, this.SuperAdminTokenOperationCompleted, userState);
        }
        
        private void OnSuperAdminTokenOperationCompleted(object arg) {
            if ((this.SuperAdminTokenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SuperAdminTokenCompleted(this, new SuperAdminTokenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDepartmentTree", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DepartmentTree GetDepartmentTree(string token, int expirationMinutes) {
            object[] results = this.Invoke("GetDepartmentTree", new object[] {
                        token,
                        expirationMinutes});
            return ((DepartmentTree)(results[0]));
        }
        
        /// <remarks/>
        public void GetDepartmentTreeAsync(string token, int expirationMinutes) {
            this.GetDepartmentTreeAsync(token, expirationMinutes, null);
        }
        
        /// <remarks/>
        public void GetDepartmentTreeAsync(string token, int expirationMinutes, object userState) {
            if ((this.GetDepartmentTreeOperationCompleted == null)) {
                this.GetDepartmentTreeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDepartmentTreeOperationCompleted);
            }
            this.InvokeAsync("GetDepartmentTree", new object[] {
                        token,
                        expirationMinutes}, this.GetDepartmentTreeOperationCompleted, userState);
        }
        
        private void OnGetDepartmentTreeOperationCompleted(object arg) {
            if ((this.GetDepartmentTreeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDepartmentTreeCompleted(this, new GetDepartmentTreeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUsersInDepartment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public User[] GetUsersInDepartment(string token, int sponsorID, int departmentID, int expirationMinutes) {
            object[] results = this.Invoke("GetUsersInDepartment", new object[] {
                        token,
                        sponsorID,
                        departmentID,
                        expirationMinutes});
            return ((User[])(results[0]));
        }
        
        /// <remarks/>
        public void GetUsersInDepartmentAsync(string token, int sponsorID, int departmentID, int expirationMinutes) {
            this.GetUsersInDepartmentAsync(token, sponsorID, departmentID, expirationMinutes, null);
        }
        
        /// <remarks/>
        public void GetUsersInDepartmentAsync(string token, int sponsorID, int departmentID, int expirationMinutes, object userState) {
            if ((this.GetUsersInDepartmentOperationCompleted == null)) {
                this.GetUsersInDepartmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUsersInDepartmentOperationCompleted);
            }
            this.InvokeAsync("GetUsersInDepartment", new object[] {
                        token,
                        sponsorID,
                        departmentID,
                        expirationMinutes}, this.GetUsersInDepartmentOperationCompleted, userState);
        }
        
        private void OnGetUsersInDepartmentOperationCompleted(object arg) {
            if ((this.GetUsersInDepartmentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUsersInDepartmentCompleted(this, new GetUsersInDepartmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ManagerLogOut", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ManagerLogOut(int sponsorAdminID, string token) {
            object[] results = this.Invoke("ManagerLogOut", new object[] {
                        sponsorAdminID,
                        token});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ManagerLogOutAsync(int sponsorAdminID, string token) {
            this.ManagerLogOutAsync(sponsorAdminID, token, null);
        }
        
        /// <remarks/>
        public void ManagerLogOutAsync(int sponsorAdminID, string token, object userState) {
            if ((this.ManagerLogOutOperationCompleted == null)) {
                this.ManagerLogOutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnManagerLogOutOperationCompleted);
            }
            this.InvokeAsync("ManagerLogOut", new object[] {
                        sponsorAdminID,
                        token}, this.ManagerLogOutOperationCompleted, userState);
        }
        
        private void OnManagerLogOutOperationCompleted(object arg) {
            if ((this.ManagerLogOutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ManagerLogOutCompleted(this, new ManagerLogOutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SponsorAdministrator : BaseModel {
        
        private System.DateTime tokenExpiresField;
        
        private int statusField;
        
        private Sponsors sponsorField;
        
        private string nameField;
        
        private bool readOnlyField;
        
        private bool seeUsersField;
        
        private bool anonymizedField;
        
        private int superAdminIdField;
        
        private string tokenField;
        
        /// <remarks/>
        public System.DateTime tokenExpires {
            get {
                return this.tokenExpiresField;
            }
            set {
                this.tokenExpiresField = value;
            }
        }
        
        /// <remarks/>
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public Sponsors Sponsor {
            get {
                return this.sponsorField;
            }
            set {
                this.sponsorField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public bool ReadOnly {
            get {
                return this.readOnlyField;
            }
            set {
                this.readOnlyField = value;
            }
        }
        
        /// <remarks/>
        public bool SeeUsers {
            get {
                return this.seeUsersField;
            }
            set {
                this.seeUsersField = value;
            }
        }
        
        /// <remarks/>
        public bool Anonymized {
            get {
                return this.anonymizedField;
            }
            set {
                this.anonymizedField = value;
            }
        }
        
        /// <remarks/>
        public int SuperAdminId {
            get {
                return this.superAdminIdField;
            }
            set {
                this.superAdminIdField = value;
            }
        }
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Sponsors : BaseModel {
        
        private string nameField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(User))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Sponsors))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SponsorAdministrator))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BaseModel {
        
        private int idField;
        
        private string[] errorsField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Department {
        
        private string tokenField;
        
        private int sponsorIDField;
        
        private string sponsorNameField;
        
        private int departmentIdField;
        
        private string departmentNameField;
        
        private int depthField;
        
        private int totalActiveField;
        
        private int activeField;
        
        private int subTotalField;
        
        private int totalField;
        
        private string firstInviteSentField;
        
        private string receiveInvitationField;
        
        private string departmentShortField;
        
        private int depthXField;
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public int SponsorID {
            get {
                return this.sponsorIDField;
            }
            set {
                this.sponsorIDField = value;
            }
        }
        
        /// <remarks/>
        public string SponsorName {
            get {
                return this.sponsorNameField;
            }
            set {
                this.sponsorNameField = value;
            }
        }
        
        /// <remarks/>
        public int DepartmentId {
            get {
                return this.departmentIdField;
            }
            set {
                this.departmentIdField = value;
            }
        }
        
        /// <remarks/>
        public string DepartmentName {
            get {
                return this.departmentNameField;
            }
            set {
                this.departmentNameField = value;
            }
        }
        
        /// <remarks/>
        public int Depth {
            get {
                return this.depthField;
            }
            set {
                this.depthField = value;
            }
        }
        
        /// <remarks/>
        public int TotalActive {
            get {
                return this.totalActiveField;
            }
            set {
                this.totalActiveField = value;
            }
        }
        
        /// <remarks/>
        public int Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        public int SubTotal {
            get {
                return this.subTotalField;
            }
            set {
                this.subTotalField = value;
            }
        }
        
        /// <remarks/>
        public int Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        public string FirstInviteSent {
            get {
                return this.firstInviteSentField;
            }
            set {
                this.firstInviteSentField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiveInvitation {
            get {
                return this.receiveInvitationField;
            }
            set {
                this.receiveInvitationField = value;
            }
        }
        
        /// <remarks/>
        public string DepartmentShort {
            get {
                return this.departmentShortField;
            }
            set {
                this.departmentShortField = value;
            }
        }
        
        /// <remarks/>
        public int DepthX {
            get {
                return this.depthXField;
            }
            set {
                this.depthXField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DepartmentTree {
        
        private int sponsorIDField;
        
        private int totalCountField;
        
        private string totalCountReceiveInvitationField;
        
        private Department[] departmentsField;
        
        /// <remarks/>
        public int SponsorID {
            get {
                return this.sponsorIDField;
            }
            set {
                this.sponsorIDField = value;
            }
        }
        
        /// <remarks/>
        public int TotalCount {
            get {
                return this.totalCountField;
            }
            set {
                this.totalCountField = value;
            }
        }
        
        /// <remarks/>
        public string TotalCountReceiveInvitation {
            get {
                return this.totalCountReceiveInvitationField;
            }
            set {
                this.totalCountReceiveInvitationField = value;
            }
        }
        
        /// <remarks/>
        public Department[] Departments {
            get {
                return this.departmentsField;
            }
            set {
                this.departmentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class User : BaseModel {
        
        private System.Nullable<System.DateTime> sentField;
        
        private string emailField;
        
        private int departmentIDField;
        
        private int userIDField;
        
        private System.Nullable<System.DateTime> stoppedField;
        
        private int stoppedReasonField;
        
        private string internalField;
        
        private string personNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Sent {
            get {
                return this.sentField;
            }
            set {
                this.sentField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public int DepartmentID {
            get {
                return this.departmentIDField;
            }
            set {
                this.departmentIDField = value;
            }
        }
        
        /// <remarks/>
        public int UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Stopped {
            get {
                return this.stoppedField;
            }
            set {
                this.stoppedField = value;
            }
        }
        
        /// <remarks/>
        public int StoppedReason {
            get {
                return this.stoppedReasonField;
            }
            set {
                this.stoppedReasonField = value;
            }
        }
        
        /// <remarks/>
        public string Internal {
            get {
                return this.internalField;
            }
            set {
                this.internalField = value;
            }
        }
        
        /// <remarks/>
        public string PersonNumber {
            get {
                return this.personNumberField;
            }
            set {
                this.personNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ManagerLoginCompletedEventHandler(object sender, ManagerLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ManagerLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ManagerLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SponsorAdministrator Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SponsorAdministrator)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void SuperAdminTokenCompletedEventHandler(object sender, SuperAdminTokenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SuperAdminTokenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SuperAdminTokenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SponsorAdministrator Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SponsorAdministrator)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetDepartmentTreeCompletedEventHandler(object sender, GetDepartmentTreeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDepartmentTreeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDepartmentTreeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DepartmentTree Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DepartmentTree)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetUsersInDepartmentCompletedEventHandler(object sender, GetUsersInDepartmentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUsersInDepartmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUsersInDepartmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public User[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((User[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ManagerLogOutCompletedEventHandler(object sender, ManagerLogOutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ManagerLogOutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ManagerLogOutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591